name: Pull from Upstream

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  pull:
    runs-on: arch-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Add upstream repository
      run: git remote add upstream https://github.com/anthraxx/linux-hardened.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/master

    - name: Push changes to origin
      run: |
        git push origin master
        # Uncomment the following lines if you are working with a different branch
        # git push origin <your-branch-name>
